apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapp-ui
  template:
    metadata:
      labels:
        app: weatherapp-ui
    spec:
      containers:
      - name: weatherapp-ui
        image: ahmddraed/weatherapp-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP

        env:
        - name: AUTH_HOST
          value: weatherapp-auth
        - name: AUTH_PORT
          value: "8080"

        - name: WEATHER_HOST
          value: weatherapp-weather
        - name: WEATHER_PORT
          value: "5000"

        livenessProbe:
          httpGet:
            path: /health
            port: 3000

        readinessProbe:
          httpGet:
          path: /health
          port: 3000