apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weatherapp-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - weatherapp.com
      secretName: weatherapp-tls
  rules:
  - host: weatherapp.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: weatherapp-ui
            port:
              number: 3000